# Generated by Django 6.0.3 on 2026-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cestas/'),
        ),
    ]
