# Generated by Django 6.0.3 on 2026-03-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_cesta_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Nome sem espaços para usar na URL (ex: dia-das-maes)', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cesta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cestas', to='loja.categoria'),
        ),
    ]
