# Generated by Django 6.0.3 on 2026-03-11 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_categoria_cesta_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='cestas/galeria/')),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_galeria', to='loja.cesta')),
            ],
        ),
    ]
