# Generated by Django 6.0.3 on 2026-04-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_imagemcesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cesta',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='cestas', to='loja.categoria'),
        ),
    ]
